IF
	InPartyAllowDead("AJANTIS")
	Global("AjantisSummonedToB","GLOBAL",1)
THEN
	RESPONSE #100
		ActionOverride("AJANTIS",ChangeAIScript("7XAjan25",OVERRIDE))
		SetGlobal("AjantisSummonedToB","GLOBAL",2)
END

IF
	InPartyAllowDead("AJANTIS")
	Global("AjantisSummonedToB","GLOBAL",0)
THEN
	RESPONSE #100
		ActionOverride("AJANTIS",ChangeAIScript("7XAjan25",OVERRIDE))
		SetGlobal("AjantisSummonedToB","GLOBAL",2)
END