IF
	InPartyAllowDead("MONTARON")
	Global("MONTISummonedTOB","GLOBAL",1)
THEN
	RESPONSE #100
		ActionOverride("MONTARON",ChangeAIScript("7XMON25",OVERRIDE))
		SetGlobal("MONTISummonedTOB","GLOBAL",2)
END

IF
	InPartyAllowDead("MONTARON")
	Global("MONTISummonedTOB","GLOBAL",0)
THEN
	RESPONSE #100
		ActionOverride("MONTARON",ChangeAIScript("7XMON25",OVERRIDE))
		SetGlobal("MONTISummonedTOB","GLOBAL",2)
END