IF
	InPartyAllowDead("GARRICK")
	Global("GarrickTOBSummon","GLOBAL",1)
THEN
	RESPONSE #100
		ActionOverride("GARRICK",ChangeAIScript("7XGar25",OVERRIDE))
		SetGlobal("GarrickTOBSummon","GLOBAL",2)
END

IF
	InPartyAllowDead("GARRICK")
	Global("GarrickTOBSummon","GLOBAL",0)
THEN
	RESPONSE #100
		ActionOverride("GARRICK",ChangeAIScript("7XGar25",OVERRIDE))
		SetGlobal("GarrickTOBSummon","GLOBAL",2)
END