// Melissan (Pocket Plane)

IF
	OR(2)
	Dead("balth") // standard 
	Global("fin_balth_checkpoint_passed","GLOBAL",1) // Ascension compatibility
	InParty("FALDORN") InMyArea("FALDORN") !StateCheck("FALDORN",CD_STATE_NOTVALID)
	Global("FaldornMelissan","AR4500",0)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!ActuallyInCombat()
THEN
	RESPONSE #100
	SetGlobal("FaldornMelissan","AR4500",1)
    ActionOverride("FALDORN",StartDialogNoSet("Player1"))
END